version: "3.6"

services:
  pre-deploy-flyway-service:
    build: .
    ports:
      - "8080:8080"

  pre-deploy-flyway-runner:
    build: .
    environment:
      LOADER_MAIN: migrate.com.vns.flyway.FlywayMigrationRunner
    command: java -cp app.jar org.springframework.boot.loader.PropertiesLauncher